version: '3'

services:
  ddns:
    container_name: dynu_dns
    build:
      context: .
      target: dynu_domain
    environment:
      - DYNU_APIKEY=${API_KEY}
      - DYNU_DOMAIN=${DOMAIN}
    restart: always
