version: '3.7'

services:
  ddns:
    container_name: dynu_dns
    build:
      context: .
      target: dynu_domain
    environment:
      - DYNU_PASSWORD=${SHA256_PASSWORD}
      - DYNU_DOMAIN=${DOMAIN}
    restart: always